### ISSUE TITLE
Real activity duration

### ISSUE THREAD

**Issue by polyvertex** [kopa/RunnersField#10]
Hi, I've been using your field intensively on a _fenix 3_ over the past few weeks and it really works like a charm so thank you for sharing it!

I've noticed that when I pause then resume an activity a bit later, the duration shown in your field takes into account the _pause_ time as well. That is, the total duration since the first _start_ of the activity, instead of just the amount of _active_ time during the current activity.

Would it be possible to get the _real_ activity duration instead of the total?

**Comment by kopa** [comment]
Thanks! I will look into this the next time I have time to work on the field.
